#!/usr/bin/python3
# Copyright The Flatcar Authors.
# SPDX-License-Identifier: Apache-2.0

import argparse
import os
import shutil
import subprocess
import sys
import re

import portage


GH_REPO = "flatcar/scripts"
GIT_LOCATION = "/home/core/scripts"


def get_release():
    """Return the version of the currently running release."""
    release = False
    with open("/usr/share/flatcar/release") as release_file:
        for line in release_file:
            if line.startswith("FLATCAR_RELEASE_VERSION="):
                release = line.split("=", 1)[1].strip().replace("+", "-", 1)

    return release


def get_channel():
    """Return the channel for the current deployment"""
    channel = None
    with open("/usr/share/flatcar/update.conf") as update_conf:
        for line in update_conf:
            if line.startswith("GROUP"):
                channel = line.split("=", 1)[1].strip()
                if channel == 'developer':
                    channel = 'main'

    return channel


def git_clone_scripts(ref):
    """Clone the scripts repo at the given location, and handle submodules (if applicable)"""
    print(f">>> Starting git clone at {ref} in {GIT_LOCATION}")
    os.umask(0o022)
    subprocess.check_call([
        "git",
        "clone",
        "--depth=1",
        "--revision", ref,
        f"https://github.com/{GH_REPO}.git", GIT_LOCATION,
    ])
    # We could handle the submodules with the clone above, but the
    # --single-branch option does not propagate.
    subprocess.check_call([
        "git", "-C", GIT_LOCATION,
        "submodule", "update",
        "--init",
        "--recursive",
        "--depth=1",
        "--single-branch",
    ])
    print(f">>> Git clone in {GIT_LOCATION} successful")


def sync_repo(revision=None):
    if revision is not None:
        ref = revision
    else:
        release = get_release()
        channel = get_channel()
        ref = f"{channel}-{release}"

        # Check if release ends with a git ref. If it does we're dealing with
        #   a dev build which does not necessarily have a tag on 'scripts'.
        # These version strings look like e.g. "3552.0.0+nightly-20230323-2100-4-g5d72f4ee",
        #   with "-g<checksum>" being a git ref.
        gitref_pat = r'-g([0-9A-Fa-f]+)$'
        ref_match = re.search(gitref_pat, release)
        if ref_match:
            git_ref = ref_match.group(1)
            print(f">>> Gitref detected in version {ref}, will check out {git_ref}.")
            ref = git_ref

    if os.path.isdir(GIT_LOCATION) and not os.path.islink(GIT_LOCATION):
        shutil.rmtree(GIT_LOCATION)
    elif os.path.lexists(GIT_LOCATION):
        os.unlink(GIT_LOCATION)

    git_clone_scripts(ref=ref)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--revision",
        help="scripts repository revision to clone instead of the release-derived ref",
    )
    args = parser.parse_args()

    try:
        sync_repo(revision=args.revision)
        # Perform normal post-sync tasks
        configroot = portage.settings["PORTAGE_CONFIGROOT"]
        post_sync = "%s/etc/portage/bin/post_sync" % configroot
        if os.path.exists(post_sync):
            subprocess.check_call([post_sync])
        subprocess.check_call(["emerge", "--check-news", "--quiet"])
    except Exception as e:
        print(e.output)
        sys.stderr.write(">>> No git repositories configured.\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
